# more specific selections for Python 3 (ASkr, 2/2018)
from launchpad_py.launchpad_to_refactor import Launchpad
from launchpad_py.launchpad_to_refactor import LaunchpadMk2
from launchpad_py.launchpad_to_refactor import LaunchpadPro
from launchpad_py.launchpad_to_refactor import LaunchControlXL
from launchpad_py.launchpad_to_refactor import LaunchControl
from launchpad_py.launchpad_to_refactor import LaunchKeyMini
from launchpad_py.launchpad_to_refactor import Dicer
from launchpad_py.launchpad_to_refactor import LaunchpadMiniMk3
from launchpad_py.launchpad_to_refactor import LaunchpadLPX
from launchpad_py.launchpad_to_refactor import MidiFighter64
from launchpad_py.launchpad_to_refactor import MidiFighter3D
from launchpad_py.launchpad_to_refactor import LaunchpadProMk3
from launchpad_py import charset
